# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_Acceptancers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='T_Docsubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='T_Doctype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='T_Executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='T_Mainexecutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainexecutor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='T_NormativAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnum', models.CharField(max_length=200)),
                ('regdate', models.DateField()),
                ('topic', models.CharField(max_length=2000)),
                ('publicateflag', models.BooleanField()),
                ('numofnewspaper', models.CharField(max_length=200)),
                ('publicatedate', models.DateField()),
                ('controldate', models.DateField()),
                ('result', models.BooleanField()),
                ('controloff', models.BooleanField()),
                ('pagescount', models.IntegerField()),
                ('addonscount', models.IntegerField()),
                ('archivedelo', models.CharField(max_length=200)),
                ('archivetom', models.CharField(max_length=200)),
                ('sheetscount', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('docsubtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor.T_Docsubtype')),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor.T_Doctype')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor.T_Executor')),
                ('mainexecutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor.T_Mainexecutor')),
            ],
        ),
        migrations.CreateModel(
            name='T_NormativAct_podchin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor.T_NormativAct')),
            ],
        ),
        migrations.CreateModel(
            name='T_NormativAct_podchin2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor.T_NormativAct')),
                ('signername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor.T_Acceptancers')),
            ],
        ),
        migrations.CreateModel(
            name='T_Publicationlocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicatedin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='T_Signers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='T_Signing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeossigning', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='T_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='T_Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='t_normativact_podchin',
            name='signername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor.T_Signers'),
        ),
        migrations.AddField(
            model_name='t_normativact',
            name='publicatedin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor.T_Publicationlocate'),
        ),
        migrations.AddField(
            model_name='t_normativact',
            name='signing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor.T_Signing'),
        ),
        migrations.AddField(
            model_name='t_normativact',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor.T_Status'),
        ),
        migrations.AddField(
            model_name='t_normativact',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor.T_Theme'),
        ),
    ]
